### ISSUE TITLE
ADT sensors not updating status

### ISSUE THREAD

**Issue by sinayion** [digitalcraig/adt-pulse-mqtt#21]
Hi,

I have the add-on set up, and I can see my entities/zones in the dashboard. All the door, window and motion sensors show up with the appropriate icons, and I'm able to arm/disarm my system.

However, the entity states are not updating at all in the addon, with the exception of the armed/disarmed status. The only way to get my door/window/motion sensors to update in the UI, is if I force a state via Developer Tools -> States.

Anything obvious I may be missing?

**Comment by digitalcraig** [comment]
Are you getting any errors in the add-on log? Something like, "::TypeError: Cannot read property '1' of null"?

**Comment by sinayion** [comment]
I just figured it out, and feel stupid. I put the zones in the binary_sensor parts in all lowercase; turns out the capitalisation matters!

Once I fixed that, the sensors now work. Thanks for this great addon.

**Comment by digitalcraig** [comment]
Awesome, glad to hear you got it sorted!
