### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by kchaney9** [digitalcraig/adt-pulse-mqtt#26]
I've checked my email and password several times and it is correct but for some reason I keep getting an authorization failed error. However when I access the pulse app on my phone, under activity, I can see the home Assistant accessing pulse every 5 seconds.

**Comment by digitalcraig** [comment]
can you post logs from docker/hassio with any identifying information removed?

**Comment by kchaney9** [comment]
I'm a noob at this so I'm not sure if this is the log your looking for but this is what I'm seeing:

5/17/2020, 1:56:11 PM Pulse: Authentication New URL Prefix /myhome/xxxxx

5/17/2020, 1:56:11 PM Pulse: Authentication  Calling https://portal.adtpulse.com/myhome/xxxxx

5/17/2020, 1:56:14 PM Pulse: Authentication Failed
5/17/2020, 1:56:14 PM Pulse: httpResponse:[object Object]
5/17/2020, 1:56:16 PM Pulse: Login called Authenticating
5/17/2020, 1:56:16 PM Pulse: Authentication Received Pathname: /myhome/xxxxx
5/17/2020, 1:56:16 PM Pulse: Authentication Page Version: xxxx
5/17/2020, 1:56:16 PM Pulse: Authentication New URL Prefix /myhome/xxxxx
5/17/2020, 1:56:16 PM Pulse: Authentication  Calling https://portal.adtpulse.com/myhome/xxxxx
5/17/2020, 1:56:19 PM Pulse: Authentication Failed
5/17/2020, 1:56:19 PM Pulse: httpResponse:[object Object]
5/17/2020, 1:56:21 PM Pulse: Login called Authenticating
5/17/2020, 1:56:21 PM Pulse: Authentication Received Pathname: /myhome/xxxxx
5/17/2020, 1:56:21 PM Pulse: Authentication Page Version: xxxxx
5/17/2020, 1:56:21 PM Pulse: Authentication New URL Prefix /myhome/xxxxx
5/17/2020, 1:56:21 PM Pulse: Authentication  Calling https://portal.adtpulse.com/myhome/xxxxx
5/17/2020, 1:56:24 PM Pulse: Authentication Failed


I've checked the logs under developer tools and there's no mention of ADT Pulse.

**Comment by digitalcraig** [comment]
The  error indicates that the correct username/password are not being sent to the ADT website. Are you using it as a standalone docker container or as a hassio addon? Can you login to the website directly (not through app)? Can you post your configuration file with username/password redacted?

**Comment by kchaney9** [comment]
I'm using it as an add-on and I am able to login to the app using the same email and password. Here's my config:

ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
pulse_login:
  username: [REDACTED]
  password: [REDACTED]
mqtt_host: core-mosquitto
mqtt_url: "" 
mqtt_connect_options:
  username: [REDACTED]
  password: [REDACTED]
alarm_state_topic: home/alarm/state
alarm_command_topic: home/alarm/cmd
ne_state_topic: adt/zone
smartthings_topic: smartthings
smartthings: false

**Comment by kchaney9** [comment]
Just noticed you said directly and not in the app and when I tried I was prompted to create security questions and now that I filled that out I'm getting a success with the authentication

**Comment by digitalcraig** [comment]
Glad you got it working!
