### ISSUE TITLE
getting one device 

### ISSUE THREAD

**Issue by gary-albano** [digitalcraig/adt-pulse-mqtt#35]
Looks like I am getting the same issue here now with this repo.

```
1/26/2021, 6:38:32 PMADT Pulse: Get zone status (via orb) success.
1/26/2021, 6:38:32 PM Sensor: sensor-2 Name: back door Tags: sensor State devStatOK
1/26/2021, 6:38:32 PM: Pushing device state: devStatOK to topic adt/zone/back door/state
1/26/2021, 6:38:32 PM Pulse.getDeviceStatus No other devices found
```

**Comment by digitalcraig** [comment]
This happened after upgrading to 2.3.1?

**Comment by gary-albano** [comment]
right after, was working fine on this repo, the other repo I get the same issue. 
I know this sounds odd, if something I can look at or do, or more info let me know.

**Comment by digitalcraig** [comment]
That is very odd. I tested thoroughly with my account and didn't have any problems. I have your source and will see if I can get to the bottom of it. Unfortunately, the libraries that were using "latest" obfuscates what the actual last working version was.

**Comment by digitalcraig** [comment]
I've found the issue, standby for a new release.

**Comment by digitalcraig** [comment]
It will take a few hours for the images to build and I'll update the version in the add-on repo.
